repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      types: [file]  # override `types: [python]`
      files: (\.py$|^SConstruct$|/SConscript$)
      args:
          - "--line-length=100"
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: mixed-line-ending
    - id: trailing-whitespace
